<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-03-14T14:17:15+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      api_keys.google.maps
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Europe/Paris',
    'api_keys' => [
        'google' => [
            'maps' => 'AIzaSyAb4i5Jk9FNqYrfD09W9hdtGgyz4ZwAQNU',
        ],
    ],
];
