<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-04-02T16:38:22+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.3.1',
    'version_db_installed' => '20171218000000',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1516197511,
        'latest_version' => '8.3.2',
        'do_page_reindex_check' => false,
    ],
    'cache' => [
        'blocks' => true,
        'assets' => false,
        'theme_css' => false,
        'overrides' => true,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ],
    'theme' => [
        'compress_preprocessor_output' => true,
        'generate_less_sourcemap' => false,
    ],
];
